jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/studentsystem?serverTimezone=GMT&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&authenticationPlugin=caching_sha2_password
jdbc.username=root
jdbc.password=Ami205600//
