# ??jwt??????????
jwt.secret-key: thisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssssthisIsASecretKeyForJWTTokenGeneration123sssssssssssssssssssssssss
# ??jwt????
jwt.ttl: 7200000
# ?????????????
jwt.token-name: token
